env:
  RUBY_VERSION: 2.3.7
  FLOW_TOKEN: ${{ secrets.FLOW_TOKEN }}
  DATABASE_USERNAME: ${{ secrets.POSTGRES_USER }}
  DATABASE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  DATABASE_HOST: ${{ secrets.POSTGRES_HOST }}
  DATABASE_NAME: ${{ secrets.POSTGRES_DB }}

name: Code Quality

on: [push]

jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    container: ruby:2.3.7
    services:
      postgres:
        image: postgres:11.6
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    steps:
      - uses: actions/checkout@v2
      - name: Install postgres client
        run: apt-get install libpq-dev
      - name: Install dependencies
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          apt-get update
          apt-get install libcurl3-dev nodejs-legacy -y
          gem update --system && gem install bundler:1.16.6
          bundle
      - name: Create database
        run: |
          bundle exec rake db:create RAILS_ENV=test
      - name: Load Schema
        run: |
          bundle exec rake db:schema:load RAILS_ENV=test
      - name: Test & Upload coverage results
        run: |
          bundler exec rake
  code-check:
    name:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: adwerx/pronto-ruby@v2.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        runners: rubocop rails_best_practices flay
        target: origin/develop